=== Zyniel/GrabAMovie/src/java/xml/conf.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT configuration (refresh_rate, movieprocessors)> 
<!ELEMENT refresh_rate (#PCDATA)>
<!ELEMENT movieprocessors (movieprocessor)>
<!ELEMENT movieprocessor (name, class, options)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT options (option*)>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option name CDATA #REQUIRED>

=== Zyniel/GrabAMovie/src/java/xml/test/conf_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../conf.dtd">
<configuration>
    <refresh_rate>1000</refresh_rate>
    <movieprocessors>
        <movieprocessor>
            <name>HDDMovieProcessor</name>
            <class>grabamovie.core.HDDMovieProcessor</class>
            <options>
                <option name="destination">D:\tmp3</option>
            </options>
        </movieprocessor>
    </movieprocessors>
</configuration>
